number: '0123456789'
symbol: "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ €"
lang_char: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'
experiment_name: 'en_filtered'
train_data: 'trainer/all_data/train'
valid_data: 'trainer/all_data/test'
manualSeed: 1111
workers: 12
batch_size: 256 #32
num_iter: 8100
valInterval: 2025
saved_model: 'trainer/saved_models/adam1kheadonly.pth'
FT: True
optim: adam            # switch to Adam for sharper fine-tune
lr: 5e-4               # moderate LR for head
beta1: 0.9
rho: 0.95
eps: 1e-8
grad_clip: 5

#Data processing
select_data: '' # this is dataset folder in train_data
batch_ratio: '1' 
total_data_usage_ratio: 1.0
batch_max_length: 34 
imgH: 64
imgW: 600
rgb: False
contrast_adjust: False
sensitive: True
PAD: True
contrast_adjust: 0.0
data_filtering_off: False

# Model Architecture
Transformation: 'None'
FeatureExtraction: 'VGG'
SequenceModeling: 'BiLSTM'
Prediction: 'CTC'
num_fiducial: 20
input_channel: 1
output_channel: 256
hidden_size: 256
decode: 'greedy'
new_prediction: False
freeze_FeatureFxtraction: True
freeze_SequenceModeling: True