# number: ''
# symbol: ''
# lang_char: ' !"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~ªÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿĀāĂăĄąĆćČčĎďĐđĒēĖėĘęĚěĞğĨĩĪīĮįİıĶķĹĺĻļĽľŁłŃńŅņŇňŒœŔŕŘřŚśŞşŠšŤťŨũŪūŮůŲųŸŹźŻżŽžƏƠơƯưȘșȚțə̇ḌḍḶḷṀṁṂṃṄṅṆṇṬṭẠạẢảẤấẦầẨẩẪẫẬậẮắẰằẲẳẴẵẶặẸẹẺẻẼẽẾếỀềỂểỄễỆệỈỉỊịỌọỎỏỐốỒồỔổỖỗỘỘỚớỜờỞởỠỡỢợỤụỦủỨứỪừỬửỮữỰựỲỳỴỵỶỷỸỹ€'
number: '0123456789'
symbol: "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ €"
lang_char: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'
experiment_name: 'a_12kaug1.0rgbtpcresattbeam'
train_data: 'all_data/train'
valid_data: 'all_data/test'
manualSeed: 1111
workers: 18
batch_size: 256 #32
num_iter: 6000
valInterval: 2000
saved_model: 'saved_models/a_6knewaug0.5rgbtpcresattbeam85acc.pth'
# saved_model: ''
FT: True
optim: adam            # switch to Adam for sharper fine-tune
lr: 5e-5              # moderate LR for head
beta1: 0.9
rho: 0.95
eps: 1e-8
grad_clip: 5 #Lowered from 5 to hopefully prevent exploding gradients

#Data processing
select_data: '' # this is dataset folder in train_data
batch_ratio: '1' 
total_data_usage_ratio: 1.0
batch_max_length: 34 
imgH: 64
imgW: 600
rgb: True
contrast_adjust: False
sensitive: True
PAD: True
contrast_adjust: 0.0
data_filtering_off: False
augment: True

# Model Architecture
Transformation: 'TPS' #TPS or None
FeatureExtraction: 'ResNet'
SequenceModeling: 'BiLSTM'
Prediction: 'Attn'
num_fiducial: 20
input_channel: 1
output_channel: 256
hidden_size: 256
decode: 'beamsearch'
# decode: 'greedy'
new_prediction: False #Set this to false when using Attn or loading models.
freeze_FeatureFxtraction: False
freeze_SequenceModeling: False
